name: Fuzz Upload Action
author: Asymmetric Research
description: Upload fuzzing data to FuzzCorp
branding:
  icon: upload-cloud
  color: blue

inputs:
  type:
    description: 'Type of data to upload (asset|bundle|corpus)'
    required: true
  path:
    description: Path to file/directory to upload
    required: true
  args:
    description: 'Arguments/flags to pass to `fuzz-up upload`'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        # Validate type input
        case "${{ inputs.type }}" in
          asset|bundle|corpus)
            echo "Type: ${{ inputs.type }}"
            ;;
          *)
            echo "Error: Invalid type '${{ inputs.type }}'. Must be one of: asset, bundle, corpus"
            exit 1
            ;;
        esac

        # Validate path exists
        if [ ! -e "${{ inputs.path }}" ]; then
          echo "Error: Path '${{ inputs.path }}' does not exist"
          exit 1
        fi

        # Validate required flags
        if [ "${{ inputs.type }}" = "corpus" ]; then
          if ! echo "${{ inputs.args }}" | grep -qE -- '--seed-corpus-group([[:space:]]+[^[:space:]-]|=[^[:space:]]+)'; then
            echo "Error: Corpus uploads must include '--seed-corpus-group <value>' or '--seed-corpus-group=<value>'"
            exit 1
          fi
        fi

        if [ "${{ inputs.type }}" = "asset" ]; then
          if ! echo "${{ inputs.args }}" | grep -qE -- '--lineage([[:space:]]+[^[:space:]-]|=[^[:space:]]+)'; then
            echo "Error: Asset uploads args must include '--lineage <value>' or '--lineage=<value>'"
            exit 1
          fi
        fi

        echo "Path: ${{ inputs.path }}"
        echo "Args: ${{ inputs.args }}"
    
    - name: Validate env
      shell: bash
      run: |
        # Validate required environment variables
        if [ -z "$FUZZ_API_ORIGIN" ] || [ -z "$FUZZ_ORGANIZATION" ] || [ -z "$FUZZ_PROJECT" ] || [ -z "$FUZZ_USER" ] || [ -z "$FUZZ_PASSWORD" ]; then
          echo "Error: Missing required FuzzCorp credentials. Set FUZZ_API_ORIGIN, FUZZ_ORGANIZATION, FUZZ_PROJECT, FUZZ_USER, and FUZZ_PASSWORD environment variables."
          exit 1
        fi

    - name: Download fuzz-up
      shell: bash
      run: |
        # Detect OS
        case "${{ runner.os }}" in
          Linux)
            OS="linux"
            ;;
          macOS)
            OS="darwin"
            ;;
          *)
            echo "Error: Unsupported OS '${{ runner.os }}'. fuzz-up only supports Linux and macOS."
            exit 1
            ;;
        esac

        # Detect architecture
        case "${{ runner.arch }}" in
          X64)
            ARCH="amd64"
            ;;
          ARM64)
            ARCH="arm64"
            ;;
          *)
            echo "Error: Unsupported architecture '${{ runner.arch }}'. fuzz-up only supports X64 (amd64) and ARM64."
            exit 1
            ;;
        esac

        BINARY_NAME="fuzz-up_${OS}_${ARCH}"
        echo "Downloading fuzz-up for $OS $ARCH..."

        if ! gh release download --repo asymmetric-research/fuzz-up --pattern "$BINARY_NAME"; then
          echo "Error: Failed to download fuzz-up release"
          exit 1
        fi

        if [ ! -f "$BINARY_NAME" ]; then
          echo "Error: Downloaded file '$BINARY_NAME' not found"
          exit 1
        fi

        mv "$BINARY_NAME" fuzz-up
        chmod +x fuzz-up
        echo "fuzz-up downloaded successfully"

    - name: Log into FuzzCorp
      shell: bash
      run: |
        fuzz-up user login

    - name: Upload to FuzzCorp
      shell: bash
      run: |
        fuzz-up upload ${{ inputs.type }} ${{ inputs.path }} ${{ inputs.args }}

